### ISSUE TITLE
Files are not provided in Tutorial of SiGPML

### ISSUE THREAD

**Issue by valdemarneto** [gemoc/gemoc-studio#1]
Hi.

I am trying to run another tutorial (SigPML: http://gemoc.github.io/gemoc-studio/publish/tutorial_sigpml/html_single/Tutorial_SigPML.html), but I noticed that the ZIP with the initial projects and even the simple files (.ecore and .odesign) that I could use to create the projects by myself are not available.
Where may I find them?

Thank you since now.

Regards,
Valdemar.

**Comment by jdeantoni** [comment]
Hi,
apart from this tutorial, you can obtain all the code of both the SigPML (and the TFSM) languages by doing: new -> example -> sigPML (or TFSM) language :)
It will deploy all the plugins in your workspace (the language workbench). Then you can do the same in the modeling WB and choose SigPML model in the example in order to obtain a simple sigpml model.

good luck

**Comment by vince012** [comment]
Hi,

The resources should now be available from the tutorial "http://gemoc.github.io/gemoc studio/publish/tutorial_sigpml/html_single/Tutorial_SigPML.html"
I will have an another look this afternoon to check if there are still other missing resources.
 
In addition to what Julien said, the current integrated Sigpml example(in studio new -> example -> sigPML) is functional but differs slightly from the tutorial's one. We will merge them soon.

Vincent

**Comment by valdemarneto** [comment]
Thank you for the answers.
I would not like to take a "pre-ready" example, but if there is another option, I can take it. Thank you.

Vincent, I tried to download, but there is a small space in your URL and because of that it did not worked. I tried to fill it with "_" or " " or "", but it did not work too.

Thank you all again.
